Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"

    #forward flask app
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    #forward postgres db
    config.vm.network "forwarded_port", guest: 5432, host: 5432

    #IP ADDRESS OF THE API DATABASE
    #THIS IS COPIED INTO THE ANSIBLE SCRIPTS FOR MAKING THE DB ENVARIONMENT VARIABLES.
    config.vm.network :private_network, ip: "172.28.128.3"

    config.vm.synced_folder "../../snailx_dev_env", "/vagrant/snailx_dev_env"
    config.vm.synced_folder "../../repos", "/vagrant/repos"

    config.vm.provision "ansible_local" do |a|
        a.playbook = "api_setup.yml"
        a.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
 
end
